# Generated by Django 3.2.7 on 2021-09-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profil_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
