# Generated by Django 3.2.7 on 2021-09-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customer_profil_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profil_pic',
            new_name='profile_pic',
        ),
    ]
